server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Endpoint de santé requis par le CDC (§6)
    location = /healthz {
        default_type application/json;
        return 200 '{"status":"ok","service":"frontend"}';
    }

    # SPA : toutes les routes retombent sur index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
